apiVersion: v1
kind: Secret
metadata: 
  name: postgres-credentials
  namespace: postgres-lab
type: Opaque
data:
  POSTGRES_USER: cGd1c2Vy
  POSTGRES_PASSWORD: cGdwYXNzd29yZDEyMw==
  POSTGRES_DB: YXBwZGI=
